import Head from 'next/head'
import Script from "next/Script";

export default function Home() {
  return (
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>Create Next App</title>
        <meta name='deScription' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <Script
          src="/js/common_scripts.js"
        />
        <Script
          src="/js/functions.js"
        />
        <Script
          src="/js/validate.js"
        />
        <Script
          src="/js/animated_canvas_min.js"
        />
      </Head>

      {/*   <Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></Script>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></Script>
      <Script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></Script>
*/}


    </main>
  )
}
